HV:
  manufacturer: "Keithley instruments"
  model: "2231A-30-3"
  serial_number: "802196102797070184"
  max_voltage: 45
  max_current: 0.1

TEC:
  manufacturer: "Keithley instruments"
  model: "2231A-30-3"
  serial_number: "802196102797170034"
  max_voltage: 20
  max_current: 1